# Generated by Django 2.2.12 on 2020-05-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='dsfwgrf',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
