# Generated by Django 2.2.12 on 2020-05-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customtext_hghghg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hghghg',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='dsfwgrf',
        ),
    ]
