# Generated by Django 2.2.12 on 2020-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200522_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='hghghgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hghghhgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='jhjhjhjh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='nhhghgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
