# Generated by Django 2.2.12 on 2020-05-22 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200522_0623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jhgkjhgkjhgkjhgkjg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='jzhgfhsfkjghrf',
        ),
    ]
