# Generated by Django 2.2.12 on 2020-05-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200522_0641"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="jhghjgfw",),
        migrations.RemoveField(model_name="user", name="jhgsafakd",),
    ]
