# Generated by Django 2.2.12 on 2020-05-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200522_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hghghgh',
        ),
    ]
