# Generated by Django 2.2.12 on 2020-05-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_hghghgh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ghghg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hghg',
        ),
    ]
